#
name: Release Images

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  workflow_dispatch:
    branches: ['main']

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build-and-push-bookworm-pg16:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - id: v_pg_graphql
        name: Get Latest PG_GraphQL Versionnumber
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: supabase/pg_graphql
      - run: echo "${{ steps.v_pg_graphql.outputs.release }}"
        shell: bash
        name: Log PG_GraphQL Versionnumber

      - name: Prepare docker
        id: prep
        run: |
          GHCR_IMAGE=ghcr.io/${{ github.repository }}
          
          echo name=GHCR_IMAGE::$GHCR_IMAGE >> $GITHUB_OUTPUT
          

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./postgres/bookworm/pg16
          push: true
          tags: ${{ steps.prep.outputs.GCHR_IMAGE }}:bookworm-pg16-${{ steps.v_pg_graphql.outputs.release }}
